### PR TITLE
Fix amount getUnitPrice

### PR DESCRIPTION
**Pull request by AlexandrePavy**
Hello, 

Bug when quantity on orderItem > 1 *

Best regards,

### CODE REVIEW

**Comment by Prometee** [comment]
Hello @AlexandrePavy thanks for your PR !

Can you explain what is the bug you are encountering ? Or add a test for it to avoid it in the futur ?

**Comment by Prometee** [comment]
Hello again @AlexandrePavy indeed there was a huge bug here, but the fix could be less verbose.
You could see the fix and the additional phpspec test related to it : https://github.com/Prometee/SyliusPayumStripeCheckoutSessionPlugin/commit/28da8ca00eea34d8e2d9f9c2bba61270cd8e26d1

**Comment by AlexandrePavy** [comment]
Hello @Prometee, your fix is unfortunately does not cover all cases more particularly because of rounding. I gonna make a more detailed issue about it.

**Comment by Prometee** [comment]
You are right. I understand now why the old Stripe gateways weren't detailing those because it can lead to those issues...

I won't be available today, are you able to add the corresponding test in the spec classes ? (Don't forget to rebase your PR first)

**Comment by Prometee** [comment]
@AlexandrePavy find some time today to commit the correction inspired by this PR : https://github.com/Prometee/SyliusPayumStripeCheckoutSessionPlugin/commit/57e3dbd35c0ed31e5eedb2a556f22c8a35570ed2

**Comment by AlexandrePavy** [comment]
perfect :+1:

**Comment by Prometee** [comment]
@AlexandrePavy ah sorry I just see your commits, the only differences are the move of the  `sprintf` to the `LineItemNameProvider` because devs need to be allowed to change this sprintf too easily.

**Comment by Prometee** [comment]
@AlexandrePavy Again thanks a lot to warn me about this huge bug ! I'm selling subscriptions one by one that's why I never get this bug on prod, but I should have seen this while coding it... My bad 😕

**Comment by AlexandrePavy** [comment]
No problem ! A big thank you for the plugin you save me hours with stripe and sylius :joy:

**Pull request closed without merging**
